<a href="https://colab.research.google.com/github/anchal-bawa/Anchal/blob/main/Copy_of_KH_ML_Aa(NaiveBayesClassifier).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

df1 =pd.read_csv("drive/My Drive/Python/RTW sample AB.csv")
df1.head()

Claim No  Occurrence No  Claim Financial Year  Agency NN Incident Date  \
0  13/005096              1                  2013       7069    01/11/2012   
1  21/013033              1                  2021      63246    29/04/2021   
2  16/005676              1                  2016    2043954    16/11/2015   
3  15/002879              1                  2015      63246    04/09/2014   
4  14/020489              2                  2014      63246    08/05/2014   

  Finalised Date  Total Paid Paid Days Lost Service Start Date  \
0     24/01/2013   $8,580.00          26.01         02/11/2012   
1     10/06/2021     $573.66              2         29/04/2021   
2     04/01/2016     $796.97           2.02         16/11/2015   
3     18/02/2015   $5,570.19             26         05/09/2014   
4     29/01/2016  $35,406.63          75.09         03/10/2014   

  Service End Date  ...                                      Mechanism  \
0       18/12/2012  ...  Muscular stress-lift, carry, put down objects   
1       30/04/2021  ...                        Falls on the same level   
2       17/11/2015  ...         Being assaulted by a person or persons   
3       10/10/2014  ...        Muscular stress with no objects handled   
4       12/01/2015  ...                        Falls on the same level   

                                          Nature  \
0      Sprains and strains of joints and muscles   
1  Open wound not including traumatic amputation   
2  Open wound not including traumatic amputation   
3      Sprains and strains of joints and muscles   
4      Sprains and strains of joints and muscles   

                                              Major  \
0  Intermediate Clerical, Sales and Service Workers   
1  Intermediate Clerical, Sales and Service Workers   
2                           Associate Professionals   
3  Intermediate Clerical, Sales and Service Workers   
4                 Tradespersons and Related Workers   

                            Occupation    Gender Date of Birth Days to RTW  \
0              Personal Care Assistant  Male        05/11/1956          46   
1  Teachers Aide (Education Assistant)  Female      18/08/1971           1   
2             Residential Care Officer  Male        07/07/1967           1   
3  Teachers Aide (Education Assistant)  Male        29/07/1973          35   
4                     General Gardener  Male        06/02/1951         101   

   RTW Category Age at Accident Date Settled  
0  RTW 13 Weeks                   55       N  
1  RTW 13 Weeks                   49       N  
2  RTW 13 Weeks                   48       N  
3  RTW 13 Weeks                   41       N  
4  RTW 26 Weeks                   63       N  

[5 rows x 25 columns]

# New section

In [ ]:
df1.shape

(23139, 25)

In [ ]:
df1.dtypes

Claim No                 object
Occurrence No             int64
Claim Financial Year      int64
Agency NN                 int64
Incident Date            object
Finalised Date           object
Total Paid               object
Paid Days Lost           object
Service Start Date       object
Service End Date         object
Injury Agency Group      object
Bodily Location Group    object
Mechanism Group          object
Nature Group             object
Bodily Location          object
Mechanism                object
Nature                   object
Major                    object
Occupation               object
Gender                   object
Date of Birth            object
Days to RTW               int64
RTW Category             object
Age at Accident Date      int64
Settled                  object
dtype: object

In [ ]:
df1.isnull().sum()

Claim No                   0
Occurrence No              0
Claim Financial Year       0
Agency NN                  0
Incident Date              0
Finalised Date             0
Total Paid                 0
Paid Days Lost             0
Service Start Date       475
Service End Date         475
Injury Agency Group        0
Bodily Location Group      0
Mechanism Group            0
Nature Group               0
Bodily Location            0
Mechanism                  0
Nature                     0
Major                      0
Occupation                 0
Gender                     0
Date of Birth              1
Days to RTW                0
RTW Category               0
Age at Accident Date       0
Settled                    0
dtype: int64

In [ ]:
df2=df1.drop(['Claim No','Claim Financial Year'],axis=1)

In [ ]:
df2['Total Paid']=df2['Total Paid'].str.replace("$","")
df2['Total Paid']=df2['Total Paid'].str.replace(",","")


<ipython-input-509-8db09d7a9cb5>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2['Total Paid']=df2['Total Paid'].str.replace("$","")


In [ ]:
df2['Total Paid'] = df2['Total Paid'].apply(lambda x : float(x))

In [ ]:
df2['Paid Days Lost'].value_counts()

1         1140
2         1101
3          773
4          573
5          492
          ... 
497.6        1
53.06        1
349.66       1
79.33        1
124.3        1
Name: Paid Days Lost, Length: 7392, dtype: int64

In [ ]:
df2['Paid Days Lost']=df2['Paid Days Lost'].str.replace(",","")
df2['Paid Days Lost'] = df2['Paid Days Lost'].apply(lambda x : float(x))

In [ ]:
df2['Injury Agency Group'].value_counts()

Animal, Human and Biological Agencies              7098
Non-powered Handtools, Appliances and Equipment    5988
Environmental Agencies                             3789
Other and Unspecified Agencies                     2405
Mobile Plant and Transport                         1174
Materials and Substances                           1143
Powered Equipment, Tools and Appliances            1034
Machinery and (Mainly) Fixed Plant                  321
Chemicals and Chemical Products                     187
Name: Injury Agency Group, dtype: int64

In [ ]:
df2['Injury Agency Group']=df2['Injury Agency Group'].apply(lambda x : 'Other' if x=='Powered Equipment, Tools and Appliances' or x=='Machinery and (Mainly) Fixed Plant' or x=='Chemicals and Chemical Products' else x)

In [ ]:
df2['Injury Agency Group'].value_counts()

Animal, Human and Biological Agencies              7098
Non-powered Handtools, Appliances and Equipment    5988
Environmental Agencies                             3789
Other and Unspecified Agencies                     2405
Other                                              1542
Mobile Plant and Transport                         1174
Materials and Substances                           1143
Name: Injury Agency Group, dtype: int64

In [ ]:
df2['Bodily Location Group'].value_counts()

Upper Limbs                                    6216
Lower Limbs                                    5255
Trunk (inc. Back)                              4450
Multiple Locations                             2799
Non-physical Locations (Psychological)         2075
Head                                           1637
Neck                                            574
Systemic Locations (eg. Nervous, Digestive)     107
Unspecified Locations                            26
Name: Bodily Location Group, dtype: int64

In [ ]:
df2['Bodily Location Group']=df2['Bodily Location Group'].apply(lambda x : 'Other' if x=='Unspecified Locations' or x=='Systemic Locations (eg. Nervous, Digestive)' or x=='Neck' or x=='Non-physical Locations (Psychological)'
or x=='Head'
 else x)

In [ ]:
df2['Bodily Location Group'].value_counts()

Upper Limbs           6216
Lower Limbs           5255
Trunk (inc. Back)     4450
Other                 4419
Multiple Locations    2799
Name: Bodily Location Group, dtype: int64

In [ ]:
df2['Mechanism Group'].value_counts()

Body Stressing                                8358
Falls, Slips and Trips of a Person            5637
Being Hit by Moving Objects                   5016
Mental Stress                                 1909
Hitting Objects with a Part of the Body       1118
Other and Unspecified Mechanisms of Injury     328
Chemicals and Other Substances                 295
Heat, Radiation and Electricity                246
Biological Factors                             205
Sound and Pressure                              27
Name: Mechanism Group, dtype: int64

In [ ]:
df2['Mechanism Group']=df2['Mechanism Group'].apply(lambda x : 'Other' if x=='Sound and Pressure' or x=='Biological Factors' or x=='Heat, Radiation and Electricity' or x=='Chemicals and Other Substances'
or x=='Other and Unspecified Mechanisms of Injury' or x=='Hitting Objects with a Part of the Body' or x=='Mental Stress'
 else x)

In [ ]:
df2['Mechanism Group'].value_counts()

Body Stressing                        8358
Falls, Slips and Trips of a Person    5637
Being Hit by Moving Objects           5016
Other                                 4128
Name: Mechanism Group, dtype: int64

In [ ]:
df2['Nature Group'].value_counts()


Sprains, Strains and Dislocations               10132
Musculoskeletal System and Connective Tissue     3525
Contusion and Crushing                           2476
Mental Disorders                                 2197
Fractures                                        1551
All Other Diseases                               1126
Open Wound                                        966
Superficial Injury                                796
Burns                                             232
Foreign body, Ear, Eye, Nose, Respiratory          88
Multiple Injuries                                  50
Name: Nature Group, dtype: int64

In [ ]:
df2['Nature Group']=df2['Nature Group'].apply(lambda x : 'Other'  if  x!='Sprains, Strains and Dislocations' else x)

In [ ]:
df2['Nature Group'].value_counts()

Other                                13007
Sprains, Strains and Dislocations    10132
Name: Nature Group, dtype: int64

In [ ]:
df2['Major'].value_counts()
df2['Major']=df2['Major'].apply(lambda x : 'Professionals' if x=='Professionals' or x=='Associate Professionals' else x )
df2['Major']=df2['Major'].apply(lambda x : x if x=='Professionals' or x=='Intermediate Clerical, Sales and Service Workers' else 'Others' )

In [ ]:
df2['Major'].value_counts()

Professionals                                       9607
Intermediate Clerical, Sales and Service Workers    8159
Others                                              5373
Name: Major, dtype: int64

In [ ]:
df2['Gender'].value_counts()
df2['Gender'].str.strip()
df3 = df2[df2.Gender != 'Unknown']

In [ ]:
df3.columns

Index(['Occurrence No', 'Agency NN', 'Incident Date', 'Finalised Date',
       'Total Paid', 'Paid Days Lost', 'Service Start Date',
       'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
       'Days to RTW', 'RTW Category', 'Age at Accident Date', 'Settled'],
      dtype='object')

In [ ]:
df3['Gender'].value_counts()

Female      14492
Male         8646
Unknown         1
Name: Gender, dtype: int64

In [ ]:

columns=['Injury Agency Group', 'Bodily Location Group','Mechanism Group','Nature Group','Major','Gender']
for i in columns:
  dummies = pd.get_dummies(i +'_'+ df3[i])
  df3=pd.concat([df3,dummies],axis=1)

In [ ]:
df3.columns

Index(['Occurrence No', 'Agency NN', 'Incident Date', 'Finalised Date',
       'Total Paid', 'Paid Days Lost', 'Service Start Date',
       'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
       'Days to RTW', 'RTW Category', 'Age at Accident Date', 'Settled',
       'Injury Agency Group_Animal, Human and Biological Agencies',
       'Injury Agency Group_Environmental Agencies',
       'Injury Agency Group_Materials and Substances',
       'Injury Agency Group_Mobile Plant and Transport',
       'Injury Agency Group_Non-powered Handtools, Appliances and Equipment',
       'Injury Agency Group_Other',
       'Injury Agency Group_Other and Unspecified Agencies',
       'Bodily Location Group_Lower Limbs',
       'Bodily Location Group_Multiple Locations',
       'Bodily Location Group_Other',
       'Bodily Location Group_Trunk (

In [ ]:
df3.drop(['Injury Agency Group', 'Bodily Location Group','Mechanism Group','Nature Group','Major','Gender'],axis=1)

Occurrence No  Agency NN Incident Date Finalised Date  Total Paid  \
0                  1       7069    01/11/2012     24/01/2013     8580.00   
1                  1      63246    29/04/2021     10/06/2021      573.66   
2                  1    2043954    16/11/2015     04/01/2016      796.97   
3                  1      63246    04/09/2014     18/02/2015     5570.19   
4                  2      63246    08/05/2014     29/01/2016    35406.63   
...              ...        ...           ...            ...         ...   
23134              1      63246    22/03/2022     26/06/2022     1470.12   
23135              1      63246    06/08/2015     09/11/2015     4730.55   
23136              1    2623845    27/07/2018     14/09/2018      943.10   
23137              1    2253554    21/03/2013     28/02/2014     2062.57   
23138              1    2623920    04/11/2021     28/11/2022   103955.89   

       Paid Days Lost Service Start Date Service End Date  \
0               26.01         02/11/2012       18/12/2012   
1                2.00         29/04/2021       30/04/2021   
2                2.02         16/11/2015       17/11/2015   
3               26.00         05/09/2014       10/10/2014   
4               75.09         03/10/2014       12/01/2015   
...               ...                ...              ...   
23134            6.00         23/03/2022       30/03/2022   
23135            5.00         10/08/2015       16/08/2015   
23136            2.00         30/07/2018       02/08/2018   
23137            3.00         22/03/2013       24/03/2013   
23138          124.30         21/11/2021       15/09/2022   

                    Bodily Location  \
0                           Stomach   
1      Head - unspecified locations   
2                              Face   
3                              Knee   
4                          Shoulder   
...                             ...   
23134     Back - other and multiple   
23135                    Lower back   
23136                        Breast   
23137                         Ankle   
23138                          Ribs   

                                           Mechanism  ...  \
0      Muscular stress-lift, carry, put down objects  ...   
1                            Falls on the same level  ...   
2             Being assaulted by a person or persons  ...   
3            Muscular stress with no objects handled  ...   
4                            Falls on the same level  ...   
...                                              ...  ...   
23134          Muscular stress while handling object  ...   
23135          Muscular stress while handling object  ...   
23136         Being assaulted by a person or persons  ...   
23137                        Falls on the same level  ...   
23138             Being hit by a person accidentally  ...   

      Mechanism Group_Falls, Slips and Trips of a Person  \
0                                                      0   
1                                                      1   
2                                                      0   
3                                                      0   
4                                                      1   
...                                                  ...   
23134                                                  0   
23135                                                  0   
23136                                                  0   
23137                                                  1   
23138                                                  0   

      Mechanism Group_Other Nature Group_Other  \
0                         0                  0   
1                         0                  1   
2                         0                  1   
3                         0                  0   
4                         0                  0   
...                     ...                ...   
23134                     0                  0   
23135                     0           

In [ ]:
df3.columns

Index(['Occurrence No', 'Agency NN', 'Incident Date', 'Finalised Date',
       'Total Paid', 'Paid Days Lost', 'Service Start Date',
       'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
       'Days to RTW', 'RTW Category', 'Age at Accident Date', 'Settled',
       'Injury Agency Group_Animal, Human and Biological Agencies',
       'Injury Agency Group_Environmental Agencies',
       'Injury Agency Group_Materials and Substances',
       'Injury Agency Group_Mobile Plant and Transport',
       'Injury Agency Group_Non-powered Handtools, Appliances and Equipment',
       'Injury Agency Group_Other',
       'Injury Agency Group_Other and Unspecified Agencies',
       'Bodily Location Group_Lower Limbs',
       'Bodily Location Group_Multiple Locations',
       'Bodily Location Group_Other',
       'Bodily Location Group_Trunk (

In [ ]:
df5=df3.drop (['Occurrence No',  'Incident Date', 'Finalised Date',
       'Service Start Date', 'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
        'Settled'
       ],axis=1)

In [ ]:
df5.columns

Index(['Agency NN', 'Total Paid', 'Paid Days Lost', 'Days to RTW',
       'RTW Category', 'Age at Accident Date',
       'Injury Agency Group_Animal, Human and Biological Agencies',
       'Injury Agency Group_Environmental Agencies',
       'Injury Agency Group_Materials and Substances',
       'Injury Agency Group_Mobile Plant and Transport',
       'Injury Agency Group_Non-powered Handtools, Appliances and Equipment',
       'Injury Agency Group_Other',
       'Injury Agency Group_Other and Unspecified Agencies',
       'Bodily Location Group_Lower Limbs',
       'Bodily Location Group_Multiple Locations',
       'Bodily Location Group_Other',
       'Bodily Location Group_Trunk (inc. Back)',
       'Bodily Location Group_Upper Limbs',
       'Mechanism Group_Being Hit by Moving Objects',
       'Mechanism Group_Body Stressing',
       'Mechanism Group_Falls, Slips and Trips of a Person',
       'Mechanism Group_Other', 'Nature Group_Other',
       'Nature Group_Sprains, Strains and

In [ ]:
df5.dtypes

Agency NN                                                                int64
Total Paid                                                             float64
Paid Days Lost                                                         float64
Days to RTW                                                              int64
RTW Category                                                            object
Age at Accident Date                                                     int64
Injury Agency Group_Animal, Human and Biological Agencies                uint8
Injury Agency Group_Environmental Agencies                               uint8
Injury Agency Group_Materials and Substances                             uint8
Injury Agency Group_Mobile Plant and Transport                           uint8
Injury Agency Group_Non-powered Handtools, Appliances and Equipment      uint8
Injury Agency Group_Other                                                uint8
Injury Agency Group_Other and Unspecified Agencies  

In [ ]:
df5['RTW Category'].value_counts()

RTW 13 Weeks        15113
Not RTW 26 Weeks     5535
RTW 26 Weeks         2491
Name: RTW Category, dtype: int64

**Drop the columns with null values**

In [ ]:
df5.isna().sum()

Agency NN                                                              0
Total Paid                                                             0
Paid Days Lost                                                         0
Days to RTW                                                            0
RTW Category                                                           0
Age at Accident Date                                                   0
Injury Agency Group_Animal, Human and Biological Agencies              0
Injury Agency Group_Environmental Agencies                             0
Injury Agency Group_Materials and Substances                           0
Injury Agency Group_Mobile Plant and Transport                         0
Injury Agency Group_Non-powered Handtools, Appliances and Equipment    0
Injury Agency Group_Other                                              0
Injury Agency Group_Other and Unspecified Agencies                     0
Bodily Location Group_Lower Limbs                  

In [ ]:
x = df5.drop(['RTW Category','Total Paid','Paid Days Lost'],axis=1)
y = df5['RTW Category']

In [ ]:
#from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it
#randomsampler = RandomOverSampler()

#x,y = randomsampler.fit_resample(X,Y)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()

In [ ]:
model1.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
print(model1.score(xtrain,ytrain))
print(model1.score(xtest,ytest))

0.9550535899504436
0.9502160760587727


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(ytrain, model1.predict(xtrain)))

print(confusion_matrix(ytest, model1.predict(xtest)))

[[ 3828     0   368]
 [    0 11317     0]
 [    0   412  1429]]
[[1226    0  113]
 [   0 3796    0]
 [   0  175  475]]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
print(classification_report(ytrain, model1.predict(xtrain)))

print(classification_report(ytest, model1.predict(xtest)))

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      0.91      0.95      4196
    RTW 13 Weeks       0.96      1.00      0.98     11317
    RTW 26 Weeks       0.80      0.78      0.79      1841

        accuracy                           0.96     17354
       macro avg       0.92      0.90      0.91     17354
    weighted avg       0.96      0.96      0.95     17354

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      0.92      0.96      1339
    RTW 13 Weeks       0.96      1.00      0.98      3796
    RTW 26 Weeks       0.81      0.73      0.77       650

        accuracy                           0.95      5785
       macro avg       0.92      0.88      0.90      5785
    weighted avg       0.95      0.95      0.95      5785



**Drop the rows with null Values**

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it
randomsampler = RandomOverSampler()

x,y = randomsampler.fit_resample(x,y)

In [ ]:
x = df5.drop(['RTW Category','Total Paid','Paid Days Lost'],axis=1)
y = df5['RTW Category']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model2 = GaussianNB()

In [ ]:
model2.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))

0.9560908147977412
0.952808988764045


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(ytrain, model2.predict(xtrain)))

print(confusion_matrix(ytest, model2.predict(xtest)))

[[ 3771     0   352]
 [    0 11356     0]
 [    0   410  1465]]
[[1280    0  132]
 [   0 3757    0]
 [   0  141  475]]


In [ ]:
print(classification_report(ytrain, model2.predict(xtrain)))

print(classification_report(ytest, model2.predict(xtest)))

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      0.91      0.96      4123
    RTW 13 Weeks       0.97      1.00      0.98     11356
    RTW 26 Weeks       0.81      0.78      0.79      1875

        accuracy                           0.96     17354
       macro avg       0.92      0.90      0.91     17354
    weighted avg       0.96      0.96      0.96     17354

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      0.91      0.95      1412
    RTW 13 Weeks       0.96      1.00      0.98      3757
    RTW 26 Weeks       0.78      0.77      0.78       616

        accuracy                           0.95      5785
       macro avg       0.92      0.89      0.90      5785
    weighted avg       0.95      0.95      0.95      5785



In [ ]:
model2.predict(xtrain)

array(['RTW 13 Weeks', 'RTW 13 Weeks', 'Not RTW 26 Weeks', ...,
       'RTW 13 Weeks', 'RTW 13 Weeks', 'RTW 13 Weeks'], dtype='<U16')

In [ ]:
model2.predict_proba(xtrain)

array([[1.86791382e-02, 9.76397563e-01, 4.92329886e-03],
       [1.45602234e-02, 9.71214003e-01, 1.42257739e-02],
       [1.00000000e+00, 2.01675008e-21, 7.64406602e-12],
       ...,
       [1.61809580e-02, 9.80153376e-01, 3.66566556e-03],
       [2.29483398e-02, 9.15991066e-01, 6.10605946e-02],
       [6.21247597e-02, 6.43772447e-01, 2.94102793e-01]])

**Tuning threshold**
****

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score
fpr,tpr,thresh = roc_curve(ytrain , model2.predict_proba(xtrain)[: , 1])

ValueError: ignored

In [ ]:
g_val = tpr * (1-fpr)
print(g_val.argmax())

NameError: ignored

In [ ]:
print(thresh[5002])

NameError: ignored

In [ ]:
model2.predict_proba(xtrain)[: , 1] > 0.55

array([ True, False, False, ...,  True, False,  True])

In [ ]:
ypredTrainThresh = np.where(model2.predict_proba(xtrain)[: , 1] > 0.55 , 1 , 0)
ypredTestThresh = np.where(model2.predict_proba(xtest)[: , 1] > 0.55 , 1 , 0)

In [ ]:
ypredTrainThresh

array([1, 0, 0, ..., 1, 0, 1])

In [ ]:
print(confusion_matrix(ytrain, ypredTrainThresh))

ValueError: ignored

In [ ]:
print(confusion_matrix(ytest, ypredTestThresh))

[[2122 2332]
 [1839 2631]]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
print(classification_report(ytrain, ypredTrainThresh))

              precision    recall  f1-score   support

           0       0.55      0.48      0.52     13394
           1       0.54      0.61      0.57     13378

    accuracy                           0.55     26772
   macro avg       0.55      0.55      0.55     26772
weighted avg       0.55      0.55      0.55     26772



In [ ]:
print(classification_report(ytest, ypredTestThresh))

              precision    recall  f1-score   support

           0       0.54      0.48      0.50      4454
           1       0.53      0.59      0.56      4470

    accuracy                           0.53      8924
   macro avg       0.53      0.53      0.53      8924
weighted avg       0.53      0.53      0.53      8924



In [ ]:
print(accuracy_score(ytrain, ypredTrainThresh))
print(accuracy_score(ytest, ypredTestThresh))

0.5477364410578216
0.532608695652174


**Use Random Forest Classifier**

In [ ]:
df5.head()

Agency NN  Total Paid  Paid Days Lost  Days to RTW  RTW Category  \
0       7069     8580.00           26.01           46  RTW 13 Weeks   
1      63246      573.66            2.00            1  RTW 13 Weeks   
2    2043954      796.97            2.02            1  RTW 13 Weeks   
3      63246     5570.19           26.00           35  RTW 13 Weeks   
4      63246    35406.63           75.09          101  RTW 26 Weeks   

   Age at Accident Date  \
0                    55   
1                    49   
2                    48   
3                    41   
4                    63   

   Injury Agency Group_Animal, Human and Biological Agencies  \
0                                                  0           
1                                                  0           
2                                                  1           
3                                                  1           
4                                                  0           

   Injury Agency Group_Environmental Agencies  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           1   

   Injury Agency Group_Materials and Substances  \
0                                             0   
1                                             0   
2                                             0   
3                                             0   
4                                             0   

   Injury Agency Group_Mobile Plant and Transport  ...  \
0                                               1  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   Mechanism Group_Falls, Slips and Trips of a Person  Mechanism Group_Other  \
0                                                  0                       0   
1                                                  1                       0   
2                                                  0                       0   
3                                                  0                       0   
4                                                  1                       0   

   Nature Group_Other  Nature Group_Sprains, Strains and Dislocations  \
0                   0                                               1   
1                   1                                               0   
2                   1                                               0   
3                   0                                               1   
4                   0                                               1   

   Major_Intermediate Clerical, Sales and Service Workers  Major_Others  \
0                                                  1                  0   
1                                                  1                  0   
2                                                  0                  0   
3                                                  1                  0   
4                                                  0                  1   

   Major_Professionals  Gender_Female    Gender_Male      Gender_Unknown   
0                    0                0                1                0  
1                    0                1                0                0  
2                    1                0                1                0  
3                    0                0                1                0  
4                    0                0                1                0  

[5 rows x 30 columns]

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it

X2 = df5.drop(['RTW Category','Total Paid','Paid Days Lost'],axis=1)
Y2 = df5['RTW Category']

randomsampler = RandomOverSampler()

x2,y2 = randomsampler.fit_resample(X2,Y2)

In [ ]:
pd.DataFrame(Y2).value_counts()

RTW Category    
RTW 13 Weeks        15113
Not RTW 26 Weeks     5535
RTW 26 Weeks         2491
dtype: int64

In [ ]:
pd.DataFrame(y2).value_counts()

RTW Category    
Not RTW 26 Weeks    15113
RTW 13 Weeks        15113
RTW 26 Weeks        15113
dtype: int64

In [ ]:
xtrain2,xtest2,ytrain2,ytest2 = train_test_split(x2,y2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
rmodel1 = RandomForestClassifier(n_estimators=20)

rmodel1.fit(xtrain2,ytrain2)

print(rmodel1.score(xtrain2,ytrain2))
print(rmodel1.score(xtest2,ytest2))


1.0
1.0


In [ ]:
print(confusion_matrix(ytrain2, rmodel1.predict(xtrain2)))

[[11375     0     0]
 [    0 11303     0]
 [    0     0 11326]]


In [ ]:
print(confusion_matrix(ytest2, rmodel1.predict(xtest2)))

[[3738    0    0]
 [   0 3810    0]
 [   0    0 3787]]


In [ ]:
print(classification_report(ytrain2, rmodel1.predict(xtrain2)))

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      1.00      1.00     11375
    RTW 13 Weeks       1.00      1.00      1.00     11303
    RTW 26 Weeks       1.00      1.00      1.00     11326

        accuracy                           1.00     34004
       macro avg       1.00      1.00      1.00     34004
    weighted avg       1.00      1.00      1.00     34004



In [ ]:
print(classification_report(ytest2, rmodel1.predict(xtest2)))

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      1.00      1.00      3738
    RTW 13 Weeks       1.00      1.00      1.00      3810
    RTW 26 Weeks       1.00      1.00      1.00      3787

        accuracy                           1.00     11335
       macro avg       1.00      1.00      1.00     11335
    weighted avg       1.00      1.00      1.00     11335

