<a href="https://colab.research.google.com/github/anchal-bawa/Anchal/blob/main/KH_ML_Aa(NaiveBayesClassifier).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Health Insurance Lead Prediction Raw Data.csv')
df.head()

ID City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0   1        C3         3213            Rented          Individual         36   
1   2        C5         1117             Owned               Joint         75   
2   3        C5         3732             Owned          Individual         32   
3   4       C24         4378             Owned               Joint         52   
4   5        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  NaN               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0

In [ ]:
df1 = df.drop('ID',axis='columns')
df1.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
1        C5         1117             Owned               Joint         75   
2        C5         3732             Owned          Individual         32   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  NaN               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0

In [ ]:
df1.shape

(50882, 13)

In [ ]:
df1.dtypes

City_Code                   object
Region_Code                  int64
Accomodation_Type           object
Reco_Insurance_Type         object
Upper_Age                    int64
Lower_Age                    int64
Is_Spouse                   object
Health Indicator            object
Holding_Policy_Duration     object
Holding_Policy_Type        float64
Reco_Policy_Cat              int64
Reco_Policy_Premium        float64
Response                     int64
dtype: object

In [ ]:
df1.isnull().sum()

City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health Indicator           11691
Holding_Policy_Duration    20251
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64

In [ ]:
df1['Health Indicator'].unique()

array(['X1', 'X2', nan, 'X4', 'X3', 'X6', 'X5', 'X8', 'X7', 'X9'],
      dtype=object)

In [ ]:
df1['Health Indicator'].value_counts()

X1    13010
X2    10332
X3     6762
X4     5743
X5     1727
X6     1280
X7      196
X8       78
X9       63
Name: Health Indicator, dtype: int64

**Drop the columns with null values**

In [ ]:
df2 = df1.dropna(axis='columns')
df2.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
1        C5         1117             Owned               Joint         75   
2        C5         3732             Owned          Individual         32   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0         36        No               22              11628.0         0  
1         22        No               22              30510.0         0  
2         32        No               19               7450.0         1  
3         48        No               19              17780.0         0  
4         44        No               16              10404.0         0

In [ ]:
df2['City_Code'].unique()

array(['C3', 'C5', 'C24', 'C8', 'C9', 'C1', 'C15', 'C28', 'C27', 'C7',
       'C20', 'C25', 'C4', 'C2', 'C34', 'C10', 'C17', 'C18', 'C16', 'C29',
       'C33', 'C26', 'C19', 'C6', 'C12', 'C13', 'C11', 'C14', 'C22',
       'C23', 'C21', 'C36', 'C32', 'C30', 'C35', 'C31'], dtype=object)

In [ ]:
t = 'C30'
int(t[1:])

30

In [ ]:
df2['City_Code'] = df2['City_Code'].apply(lambda x : int(x[1:]))

<ipython-input-84-38a6c4d76b1e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['City_Code'] = df2['City_Code'].apply(lambda x : int(x[1:]))


In [ ]:
df2.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0          3         3213            Rented          Individual         36   
1          5         1117             Owned               Joint         75   
2          5         3732             Owned          Individual         32   
3         24         4378             Owned               Joint         52   
4          8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0         36        No               22              11628.0         0  
1         22        No               22              30510.0         0  
2         32        No               19               7450.0         1  
3         48        No               19              17780.0         0  
4         44        No               16              10404.0         0

In [ ]:
print(df2['Accomodation_Type'].unique())
print(df2['Reco_Insurance_Type'].unique())
print(df2['Is_Spouse'].unique())

['Rented' 'Owned']
['Individual' 'Joint']
['No' 'Yes']


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

encoding_columns = ['Accomodation_Type','Reco_Insurance_Type','Is_Spouse']

for col in encoding_columns:
  df2[col] = encoder.fit(df2[col]).transform(df2[col])

<ipython-input-87-28374cc57e10>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col] = encoder.fit(df2[col]).transform(df2[col])


In [ ]:
df2.head()

City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  \
0          3         3213                  1                    0         36   
1          5         1117                  0                    1         75   
2          5         3732                  0                    0         32   
3         24         4378                  0                    1         52   
4          8         2190                  1                    0         44   

   Lower_Age  Is_Spouse  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0         36          0               22              11628.0         0  
1         22          0               22              30510.0         0  
2         32          0               19               7450.0         1  
3         48          0               19              17780.0         0  
4         44          0               16              10404.0         0

In [ ]:
df2['Response'].value_counts()

0    38673
1    12209
Name: Response, dtype: int64

In [ ]:
#sns.pairplot(df2 , hue='Response')

In [ ]:
df2.isnull().sum()

City_Code              0
Region_Code            0
Accomodation_Type      0
Reco_Insurance_Type    0
Upper_Age              0
Lower_Age              0
Is_Spouse              0
Reco_Policy_Cat        0
Reco_Policy_Premium    0
Response               0
dtype: int64

In [ ]:
df2.dtypes

City_Code                int64
Region_Code              int64
Accomodation_Type        int64
Reco_Insurance_Type      int64
Upper_Age                int64
Lower_Age                int64
Is_Spouse                int64
Reco_Policy_Cat          int64
Reco_Policy_Premium    float64
Response                 int64
dtype: object

In [ ]:
X = df2.drop('Response',axis=1)
Y = df2['Response']

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it
randomsampler = RandomOverSampler()

x,y = randomsampler.fit_resample(X,Y)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()

In [ ]:
model1.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
print(model1.score(xtrain,ytrain))
print(model1.score(xtest,ytest))

0.5501215328655898
0.5453793246108497


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(ytrain, model1.predict(xtrain)))

print(confusion_matrix(ytest, model1.predict(xtest)))

[[ 8739 20201]
 [ 5896 23173]]
[[2866 6867]
 [1924 7680]]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
print(classification_report(ytrain, model1.predict(xtrain)))

print(classification_report(ytest, model1.predict(xtest)))

              precision    recall  f1-score   support

           0       0.60      0.30      0.40     28940
           1       0.53      0.80      0.64     29069

    accuracy                           0.55     58009
   macro avg       0.57      0.55      0.52     58009
weighted avg       0.57      0.55      0.52     58009

              precision    recall  f1-score   support

           0       0.60      0.29      0.39      9733
           1       0.53      0.80      0.64      9604

    accuracy                           0.55     19337
   macro avg       0.56      0.55      0.52     19337
weighted avg       0.56      0.55      0.51     19337



**Drop the rows with null Values**

In [ ]:
df1.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
1        C5         1117             Owned               Joint         75   
2        C5         3732             Owned          Individual         32   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  NaN               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0

In [ ]:
df3 = df1.dropna(axis='rows')

In [ ]:
df3.shape

(23548, 13)

In [ ]:
df3['Response'].value_counts()

0    17848
1     5700
Name: Response, dtype: int64

In [ ]:
df3.isnull().sum()

City_Code                  0
Region_Code                0
Accomodation_Type          0
Reco_Insurance_Type        0
Upper_Age                  0
Lower_Age                  0
Is_Spouse                  0
Health Indicator           0
Holding_Policy_Duration    0
Holding_Policy_Type        0
Reco_Policy_Cat            0
Reco_Policy_Premium        0
Response                   0
dtype: int64

In [ ]:
df3.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   
5        C9         1785            Rented          Individual         52   
7        C1         3175             Owned               Joint         75   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   
5         52        No               X2                     5.0   
7         73       Yes               X4                     9.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0  
5                  1.0               22              15264.0         1  
7                  4.0               17              29344.0         1

In [ ]:
df3['City_Code'] = df3['City_Code'].apply(lambda x : int(x[1:]))

<ipython-input-107-b355fd10d6ba>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['City_Code'] = df3['City_Code'].apply(lambda x : int(x[1:]))


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

encoding_columns = ['Accomodation_Type','Reco_Insurance_Type','Is_Spouse']

for col in encoding_columns:
  df3[col] = encoder.fit(df3[col]).transform(df3[col])

<ipython-input-108-8f27083d89d4>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[col] = encoder.fit(df3[col]).transform(df3[col])


In [ ]:
df3.head()

City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  \
0          3         3213                  1                    0         36   
3         24         4378                  0                    1         52   
4          8         2190                  1                    0         44   
5          9         1785                  1                    0         52   
7          1         3175                  0                    1         75   

   Lower_Age  Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36          0               X1                     14+   
3         48          0               X1                     14+   
4         44          0               X2                     3.0   
5         52          0               X2                     5.0   
7         73          1               X4                     9.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0  
5                  1.0               22              15264.0         1  
7                  4.0               17              29344.0         1

In [ ]:
df3.dtypes

City_Code                    int64
Region_Code                  int64
Accomodation_Type            int64
Reco_Insurance_Type          int64
Upper_Age                    int64
Lower_Age                    int64
Is_Spouse                    int64
Health Indicator            object
Holding_Policy_Duration     object
Holding_Policy_Type        float64
Reco_Policy_Cat              int64
Reco_Policy_Premium        float64
Response                     int64
dtype: object

In [ ]:
print(df3['Health Indicator'].unique())
print(df3['Holding_Policy_Duration'].unique())

['X1' 'X2' 'X4' 'X3' 'X5' 'X6' 'X8' 'X7' 'X9']
['14+' '3.0' '5.0' '9.0' '14.0' '2.0' '11.0' '1.0' '7.0' '10.0' '8.0'
 '6.0' '4.0' '13.0' '12.0']


In [ ]:
df3['Holding_Policy_Duration'].value_counts()

1.0     3439
2.0     3330
14+     3323
3.0     2756
4.0     2134
5.0     1828
6.0     1465
7.0     1220
8.0     1007
9.0      854
10.0     618
11.0     424
13.0     402
12.0     386
14.0     362
Name: Holding_Policy_Duration, dtype: int64

In [ ]:
df3['Holding_Policy_Duration'] = df3['Holding_Policy_Duration'].apply(lambda x : float(x[0:2]))

<ipython-input-113-de3a7bdfe99c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Holding_Policy_Duration'] = df3['Holding_Policy_Duration'].apply(lambda x : float(x[0:2]))


In [ ]:
df3['Holding_Policy_Duration'].value_counts()

14.0    3685
1.0     3439
2.0     3330
3.0     2756
4.0     2134
5.0     1828
6.0     1465
7.0     1220
8.0     1007
9.0      854
10.0     618
11.0     424
13.0     402
12.0     386
Name: Holding_Policy_Duration, dtype: int64

In [ ]:
dfh = pd.get_dummies(df3['Health Indicator'])
dfh.head()

X1  X2  X3  X4  X5  X6  X7  X8  X9
0   1   0   0   0   0   0   0   0   0
3   1   0   0   0   0   0   0   0   0
4   0   1   0   0   0   0   0   0   0
5   0   1   0   0   0   0   0   0   0
7   0   0   0   1   0   0   0   0   0

In [ ]:
df4 = pd.concat((df3,dfh) , axis='columns').drop('Health Indicator',axis=1)
df4.head()

City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  \
0          3         3213                  1                    0         36   
3         24         4378                  0                    1         52   
4          8         2190                  1                    0         44   
5          9         1785                  1                    0         52   
7          1         3175                  0                    1         75   

   Lower_Age  Is_Spouse  Holding_Policy_Duration  Holding_Policy_Type  \
0         36          0                     14.0                  3.0   
3         48          0                     14.0                  3.0   
4         44          0                      3.0                  1.0   
5         52          0                      5.0                  1.0   
7         73          1                      9.0                  4.0   

   Reco_Policy_Cat  ...  Response  X1  X2  X3  X4  X5  X6  X7  X8  X9  
0               22  ...         0   1   0   0   0   0   0   0   0   0  
3               19  ...         0   1   0   0   0   0   0   0   0   0  
4               16  ...         0   0   1   0   0   0   0   0   0   0  
5               22  ...         1   0   1   0   0   0   0   0   0   0  
7               17  ...         1   0   0   0   1   0   0   0   0   0  

[5 rows x 21 columns]

In [ ]:
X = df4.drop('Response' , axis=1)
Y = df4['Response']

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it
randomsampler = RandomOverSampler()

x,y = randomsampler.fit_resample(X,Y)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model2 = GaussianNB()

In [ ]:
model2.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))

0.55442253100254
0.5484087852980726


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(ytrain, model2.predict(xtrain)))

print(confusion_matrix(ytest, model2.predict(xtest)))

[[ 4456  8938]
 [ 2991 10387]]
[[1440 3014]
 [1016 3454]]


In [ ]:
print(classification_report(ytrain, model2.predict(xtrain)))

print(classification_report(ytest, model2.predict(xtest)))

              precision    recall  f1-score   support

           0       0.60      0.33      0.43     13394
           1       0.54      0.78      0.64     13378

    accuracy                           0.55     26772
   macro avg       0.57      0.55      0.53     26772
weighted avg       0.57      0.55      0.53     26772

              precision    recall  f1-score   support

           0       0.59      0.32      0.42      4454
           1       0.53      0.77      0.63      4470

    accuracy                           0.55      8924
   macro avg       0.56      0.55      0.52      8924
weighted avg       0.56      0.55      0.52      8924



In [ ]:
model2.predict(xtrain)

array([0, 1, 0, ..., 1, 0, 1])

In [ ]:
model2.predict_proba(xtrain)

array([[0.65071146, 0.34928854],
       [0.41898457, 0.58101543],
       [0.55479754, 0.44520246],
       ...,
       [0.42793437, 0.57206563],
       [0.73997568, 0.26002432],
       [0.38354501, 0.61645499]])

**Tuning threshold**
****

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score
fpr,tpr,thresh = roc_curve(ytrain , model2.predict_proba(xtrain)[: , 1])

In [ ]:
g_val = tpr * (1-fpr)
print(g_val.argmax())

5002


In [ ]:
print(thresh[5002])

0.5543855398973796


In [ ]:
model2.predict_proba(xtrain)[: , 1] > 0.55

array([False,  True, False, ...,  True, False,  True])

In [ ]:
ypredTrainThresh = np.where(model2.predict_proba(xtrain)[: , 1] > 0.55 , 1 , 0)
ypredTestThresh = np.where(model2.predict_proba(xtest)[: , 1] > 0.55 , 1 , 0)

In [ ]:
ypredTrainThresh

array([0, 1, 0, ..., 1, 0, 1])

In [ ]:
print(confusion_matrix(ytrain, ypredTrainThresh))

[[6494 6900]
 [5208 8170]]


In [ ]:
print(confusion_matrix(ytest, ypredTestThresh))

[[2122 2332]
 [1839 2631]]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
print(classification_report(ytrain, ypredTrainThresh))

              precision    recall  f1-score   support

           0       0.55      0.48      0.52     13394
           1       0.54      0.61      0.57     13378

    accuracy                           0.55     26772
   macro avg       0.55      0.55      0.55     26772
weighted avg       0.55      0.55      0.55     26772



In [ ]:
print(classification_report(ytest, ypredTestThresh))

              precision    recall  f1-score   support

           0       0.54      0.48      0.50      4454
           1       0.53      0.59      0.56      4470

    accuracy                           0.53      8924
   macro avg       0.53      0.53      0.53      8924
weighted avg       0.53      0.53      0.53      8924



In [ ]:
print(accuracy_score(ytrain, ypredTrainThresh))
print(accuracy_score(ytest, ypredTestThresh))

0.5477364410578216
0.532608695652174


**Use Random Forest Classifier**

In [ ]:
df2.head()

City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  \
0          3         3213                  1                    0         36   
1          5         1117                  0                    1         75   
2          5         3732                  0                    0         32   
3         24         4378                  0                    1         52   
4          8         2190                  1                    0         44   

   Lower_Age  Is_Spouse  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0         36          0               22              11628.0         0  
1         22          0               22              30510.0         0  
2         32          0               19               7450.0         1  
3         48          0               19              17780.0         0  
4         44          0               16              10404.0         0

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it

X2 = df2.drop('Response' , axis=1)
Y2 = df2['Response']

randomsampler = RandomOverSampler()

x2,y2 = randomsampler.fit_resample(X2,Y2)

In [ ]:
pd.DataFrame(Y2).value_counts()

Response
0           38673
1           12209
dtype: int64

In [ ]:
pd.DataFrame(y2).value_counts()

Response
0           38673
1           38673
dtype: int64

In [ ]:
xtrain2,xtest2,ytrain2,ytest2 = train_test_split(x2,y2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
rmodel1 = RandomForestClassifier(n_estimators=20)

rmodel1.fit(xtrain2,ytrain2)

print(rmodel1.score(xtrain2,ytrain2))
print(rmodel1.score(xtest2,ytest2))


0.9990173938526781
0.886073330919998


In [ ]:
print(confusion_matrix(ytrain2, rmodel1.predict(xtrain2)))

[[29004    13]
 [   44 28948]]


In [ ]:
print(confusion_matrix(ytest2, rmodel1.predict(xtest2)))

[[8163 1493]
 [ 710 8971]]


In [ ]:
print(classification_report(ytrain2, rmodel1.predict(xtrain2)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     29017
           1       1.00      1.00      1.00     28992

    accuracy                           1.00     58009
   macro avg       1.00      1.00      1.00     58009
weighted avg       1.00      1.00      1.00     58009



In [ ]:
print(classification_report(ytest2, rmodel1.predict(xtest2)))

              precision    recall  f1-score   support

           0       0.92      0.85      0.88      9656
           1       0.86      0.93      0.89      9681

    accuracy                           0.89     19337
   macro avg       0.89      0.89      0.89     19337
weighted avg       0.89      0.89      0.89     19337



****
**When rows with null values were dropped**

In [ ]:
df4.head()

City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  \
0          3         3213                  1                    0         36   
3         24         4378                  0                    1         52   
4          8         2190                  1                    0         44   
5          9         1785                  1                    0         52   
7          1         3175                  0                    1         75   

   Lower_Age  Is_Spouse  Holding_Policy_Duration  Holding_Policy_Type  \
0         36          0                     14.0                  3.0   
3         48          0                     14.0                  3.0   
4         44          0                      3.0                  1.0   
5         52          0                      5.0                  1.0   
7         73          1                      9.0                  4.0   

   Reco_Policy_Cat  ...  Response  X1  X2  X3  X4  X5  X6  X7  X8  X9  
0               22  ...         0   1   0   0   0   0   0   0   0   0  
3               19  ...         0   1   0   0   0   0   0   0   0   0  
4               16  ...         0   0   1   0   0   0   0   0   0   0  
5               22  ...         1   0   1   0   0   0   0   0   0   0  
7               17  ...         1   0   0   0   1   0   0   0   0   0  

[5 rows x 21 columns]

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it

X3 = df4.drop('Response' , axis=1)
Y3 = df4['Response']

randomsampler = RandomOverSampler()

x3,y3 = randomsampler.fit_resample(X3,Y3)

In [ ]:
xtrain3,xtest3,ytrain3,ytest3 = train_test_split(x3,y3,random_state=0)

from sklearn.ensemble import RandomForestClassifier
rmodel2 = RandomForestClassifier(n_estimators=20)

rmodel2.fit(xtrain3,ytrain3)

print(rmodel2.score(xtrain3,ytrain3))
print(rmodel2.score(xtest3,ytest3))

0.999589122964291
0.8999327655759749


In [ ]:
print(classification_report(ytrain3, rmodel2.predict(xtrain3)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13416
           1       1.00      1.00      1.00     13356

    accuracy                           1.00     26772
   macro avg       1.00      1.00      1.00     26772
weighted avg       1.00      1.00      1.00     26772



In [ ]:
print(classification_report(ytest3, rmodel2.predict(xtest3)))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      4432
           1       0.89      0.91      0.90      4492

    accuracy                           0.90      8924
   macro avg       0.90      0.90      0.90      8924
weighted avg       0.90      0.90      0.90      8924



**Fix null Values by filling it with mean or mode**

In [ ]:
df1.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
1        C5         1117             Owned               Joint         75   
2        C5         3732             Owned          Individual         32   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator Holding_Policy_Duration  \
0         36        No               X1                     14+   
1         22        No               X2                     NaN   
2         32        No              NaN                     1.0   
3         48        No               X1                     14+   
4         44        No               X2                     3.0   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  NaN               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0

In [ ]:
df1['Health Indicator'].mode()[0]

'X1'

In [ ]:
df1['Health Indicator'] = df1['Health Indicator'].fillna(df1['Health Indicator'].mode()[0])

In [ ]:
df1['Holding_Policy_Duration'].unique()

array(['14+', nan, '1.0', '3.0', '5.0', '9.0', '14.0', '7.0', '2.0',
       '11.0', '10.0', '8.0', '6.0', '4.0', '13.0', '12.0'], dtype=object)

In [ ]:
df1['Holding_Policy_Duration'] = df1['Holding_Policy_Duration'].str.replace('+','_')
df1['Holding_Policy_Duration'] = df1['Holding_Policy_Duration'].str.replace('14_','15')

<ipython-input-247-52a1774aea9f>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1['Holding_Policy_Duration'] = df1['Holding_Policy_Duration'].str.replace('+','_')


In [ ]:
df1['Holding_Policy_Duration'].unique()

array(['15', nan, '1.0', '3.0', '5.0', '9.0', '14.0', '7.0', '2.0',
       '11.0', '10.0', '8.0', '6.0', '4.0', '13.0', '12.0'], dtype=object)

In [ ]:
df1['Holding_Policy_Duration'] = df1['Holding_Policy_Duration'].astype(float)
df1['Holding_Policy_Duration'] = df1['Holding_Policy_Duration'].fillna(df1['Holding_Policy_Duration'].mean())

In [ ]:
df1['Holding_Policy_Type'].unique()

array([ 3., nan,  1.,  4.,  2.])

In [ ]:
df1['Holding_Policy_Type'].mean()
df1['Holding_Policy_Type'].median()

3.0

In [ ]:
df1['Holding_Policy_Type'] = df1['Holding_Policy_Type'].fillna(df1['Holding_Policy_Type'].mode()[0])

In [ ]:
df1.head()

City_Code  Region_Code Accomodation_Type Reco_Insurance_Type  Upper_Age  \
0        C3         3213            Rented          Individual         36   
1        C5         1117             Owned               Joint         75   
2        C5         3732             Owned          Individual         32   
3       C24         4378             Owned               Joint         52   
4        C8         2190            Rented          Individual         44   

   Lower_Age Is_Spouse Health Indicator  Holding_Policy_Duration  \
0         36        No               X1                15.000000   
1         22        No               X2                 6.156769   
2         32        No               X1                 1.000000   
3         48        No               X1                15.000000   
4         44        No               X2                 3.000000   

   Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response  
0                  3.0               22              11628.0         0  
1                  3.0               22              30510.0         0  
2                  1.0               19               7450.0         1  
3                  3.0               19              17780.0         0  
4                  1.0               16              10404.0         0

In [ ]:
df1.dtypes

City_Code                   object
Region_Code                  int64
Accomodation_Type           object
Reco_Insurance_Type         object
Upper_Age                    int64
Lower_Age                    int64
Is_Spouse                   object
Health Indicator            object
Holding_Policy_Duration    float64
Holding_Policy_Type        float64
Reco_Policy_Cat              int64
Reco_Policy_Premium        float64
Response                     int64
dtype: object